name: Check New Release

on:
  schedule:
    - cron: "14 */4 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: fregante/setup-git-user@v1

      - name: Fetch latest release (including pre-release)
        run: |
          curl -sfL -m 60 ${{ github.api_url }}/repos/telegramdesktop/tdesktop/releases | jq -r '[.[] | select(.draft == false)][0].tag_name' > /tmp/latest_tag

      - name: Check if branch exists
        id: check-branch
        run: |
          echo latest_tag=$(cat /tmp/latest_tag)
          http_code=$(curl -sL -m 60 -o /tmp/branch.json -w "%{http_code}" ${{ github.api_url }}/repos/${{ github.repository }}/branches/"$(cat /tmp/latest_tag)")
          echo http_code="$http_code"
          echo ::set-output name=http_code::"$http_code"
          echo "body=$(cat /tmp/branch.json)"
          echo ::set-output name=message::"$(jq -r '.message' /tmp/branch.json)"

      - name: Make new branch if not exists
        if: steps.check-branch.outputs.http_code == '404' && steps.check-branch.outputs.message == 'Branch not found'
        run: |
          latest_tag=$(cat /tmp/latest_tag)
          git remote add upstream https://github.com/telegramdesktop/tdesktop.git
          git fetch upstream
          git fetch --unshallow origin
          git checkout "refs/tags/$latest_tag"
          git checkout -b "$latest_tag"
          find .github/workflows/ -type f ! -name win.yml -delete
          git commit -am "Remove all workflows except win.yml"
          git cherry-pick 905ef082..5b6946d6
          git push origin refs/heads/"$latest_tag"
