name: Check New Release

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Check if branch exists
        id: check-branch
        run: |
          latest_tag=$(curl -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sfL -m 60 ${{ github.api_url }}/repos/telegramdesktop/tdesktop/releases/latest | jq -r '.tag_name')
          echo ::set-output name=latest_tag::"$latest_tag"
          http_code=$(curl -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sL -m 60 -o /tmp/branch.json -w "%{http_code}" ${{ github.api_url }}/repos/${{ github.repository }}/branches/"$latest_tag")
          echo http_code="$http_code"
          echo "body=$(cat /tmp/branch.json)"
          branch_not_found=false
          if [[ "$http_code" == '404' && "$(jq -r '.message' /tmp/branch.json)" == 'Branch not found' ]]; then
            branch_not_found=true
          fi
          echo ::set-output name=not_found::"$branch_not_found"

      - uses: fregante/setup-git-user@v1
        if: steps.check-branch.outputs.not_found == 'true'

      - name: Checkout new branch if not exists
        if: steps.check-branch.outputs.not_found == 'true'
        env:
          latest_tag: ${{ steps.check-branch.outputs.latest_tag }}
        run: |
          git remote add upstream https://github.com/telegramdesktop/tdesktop.git
          git fetch upstream
          git fetch --unshallow origin
          git checkout "refs/tags/$latest_tag"
          git checkout -b "${latest_tag}-my"
          find .github/workflows/ -type f ! -name win.yml -delete
          git commit -am "Remove all workflows except win.yml"
          git cherry-pick 4e39d917e90bd5f8676e352548635973521d462c^..b0e5ccf8a35fd5ce3e5c9fb8d6fde330dfb066df
          git push origin refs/heads/"${latest_tag}-my"
