name: Windows.

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'

jobs:

  windows:
    name: Windows
    runs-on: windows-2022

    strategy:
      matrix:
        arch: [Win32, x64]

    env:
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories.
        run: |
          mkdir %userprofile%\TBuild Libraries
          mklink /d %userprofile%\TBuild\Libraries %GITHUB_WORKSPACE%\Libraries
          echo TBUILD=%userprofile%\TBuild>>%GITHUB_ENV%

      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1.10.0
        name: Native Tools Command Prompt.
        with:
          arch: ${{ matrix.arch }}

      - name: Clone.
        uses: LebedevRI/checkout@issue197
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: Modify cmake scripts
        shell: bash
        working-directory: ${{ env.TBUILD }}\${{ env.REPO_NAME }}
        run: |
          patch -t -l cmake/options_win.cmake << 'EOF'
          --- options_win.cmake.a 2022-09-18 17:33:18.359920100 +0800
          +++ options_win.cmake.b 2022-09-18 21:58:49.282254900 +0800
          @@ -20,7 +20,7 @@
                  # /Qspectre
                  /W1
                  /WX
          -        /MP     # Enable multi process build.
          +        /bigobj # scheme.cpp has too many sections.
                  /EHsc   # Catch C++ exceptions only, extern C functions never throw a C++ exception.
                  /w14834 # [[nodiscard]]
                  /w15038 # wrong initialization order
          @@ -42,13 +42,14 @@
              if (build_win64)
                  target_compile_options(common_options
                  INTERFACE
          -            /bigobj # scheme.cpp has too many sections.
          +            /MP     # Enable multi process build.
                  )
              else()
          -        # target_compile_options(common_options
          -        # INTERFACE
          +        target_compile_options(common_options
          +        INTERFACE
          +            /MP1    # Limit one compiler process to avoid out of heap
                  #     /fp:except # Crash-report fp exceptions in 32 bit build.
          -        # )
          +        )
                  target_link_options(common_options
                  INTERFACE
                      /LARGEADDRESSAWARE # Allow more than 2 GB in 32 bit application.
          EOF

      - name: Python installs.
        run: pip3 install --upgrade pywin32 six

      - name: Set up environment paths.
        shell: bash
        run: |
          echo "CACHE_KEY=$(sha256sum $TBUILD/$REPO_NAME/$PREPARE_PATH | awk '{ print $1 }')" >> $GITHUB_ENV

          echo "Configurate git for cherry-picks."
          git config --global user.email "you@example.com"
          git config --global user.name "Sample"

      - name: NuGet sources.
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: Libraries cache.
        id: cache-libs
        uses: actions/cache@v2
        with:
          path: Libraries
          key: ${{ runner.OS }}-${{ matrix.arch }}-libs-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-${{ matrix.arch }}-libs-

      - name: Libraries.
        env:
          GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\'
          GYP_MSVS_VERSION: 2022
        run: '%TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat silent'

      - name: Read defines.
        shell: bash
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=Telegram_${{ matrix.arch }}_${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram_${{ matrix.arch }}" >> $GITHUB_ENV
          fi
          echo "TDESKTOP_BUILD_DEFINE=$DEFINE" >> $GITHUB_ENV

      - name: Free up some disk space.
        run: |
          del /S Libraries\*.pdb
          del /S Libraries\*.pch
          del /S Libraries\*.obj

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          C:
          cd %TBUILD%\%REPO_NAME%\Telegram

          call configure.bat ^
          ${{ matrix.arch }} ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON ^
          -D DESKTOP_APP_NO_PDB=ON ^
          -D DESKTOP_APP_DISABLE_SPELLCHECK=ON ^
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON ^
          -D TDESKTOP_API_ID=${{ secrets.TG_API_ID }} ^
          -D TDESKTOP_API_HASH=${{ secrets.TG_API_HASH }} ^
          %TDESKTOP_BUILD_DEFINE% ^
          -DCMAKE_SYSTEM_VERSION=%SDK%

          cd ..\out
          msbuild -m Telegram.sln /p:Configuration=Release,Platform=${{ matrix.arch }},DebugSymbols=false,DebugType=none

      - name: Move artifact.
        if: env.ONLY_CACHE == 'false'
        run: |
          mkdir artifact
          move %TBUILD%\%REPO_NAME%\out\Release\Telegram.exe artifact/${{ env.ARTIFACT_NAME }}.exe
      - uses: actions/upload-artifact@master
        name: Upload artifact.
        if: env.ONLY_CACHE == 'false'
        with:
          name: ${{ env.ARTIFACT_NAME }}.exe
          path: artifact\

      - name: Create Release
        if: env.ONLY_CACHE == 'false'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: artifact\*.exe
          artifactContentType: application/vnd.microsoft.portable-executable
          body: "https://github.com/telegramdesktop/tdesktop/releases/tag/${{ github.ref_name }}"
          name:  ${{ github.ref_name }}
          tag:  ${{ github.ref_name }}
          commit:  ${{ github.ref_name }}
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          prerelease: true
          replacesArtifacts: false
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
